// Code generated by protoc-gen-go. DO NOT EDIT.
// source: push.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	push.proto

It has these top-level messages:
	PushReq
	PushResp
	CometPingReq
	CometPingResp
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type PushReq struct {
	Key      string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Expire   string `protobuf:"bytes,2,opt,name=expire" json:"expire,omitempty"`
	PushUtc  string `protobuf:"bytes,3,opt,name=pushUtc" json:"pushUtc,omitempty"`
	Cert     string `protobuf:"bytes,4,opt,name=cert" json:"cert,omitempty"`
	Platform string `protobuf:"bytes,5,opt,name=platform" json:"platform,omitempty"`
	Phone    string `protobuf:"bytes,6,opt,name=phone" json:"phone,omitempty"`
	Msg      string `protobuf:"bytes,7,opt,name=msg" json:"msg,omitempty"`
	PushId   string `protobuf:"bytes,8,opt,name=pushId" json:"pushId,omitempty"`
	Topic    string `protobuf:"bytes,9,opt,name=topic" json:"topic,omitempty"`
	Callback string `protobuf:"bytes,10,opt,name=callback" json:"callback,omitempty"`
	Code     string `protobuf:"bytes,11,opt,name=code" json:"code,omitempty"`
}

func (m *PushReq) Reset()                    { *m = PushReq{} }
func (m *PushReq) String() string            { return proto1.CompactTextString(m) }
func (*PushReq) ProtoMessage()               {}
func (*PushReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PushReq) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *PushReq) GetExpire() string {
	if m != nil {
		return m.Expire
	}
	return ""
}

func (m *PushReq) GetPushUtc() string {
	if m != nil {
		return m.PushUtc
	}
	return ""
}

func (m *PushReq) GetCert() string {
	if m != nil {
		return m.Cert
	}
	return ""
}

func (m *PushReq) GetPlatform() string {
	if m != nil {
		return m.Platform
	}
	return ""
}

func (m *PushReq) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *PushReq) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *PushReq) GetPushId() string {
	if m != nil {
		return m.PushId
	}
	return ""
}

func (m *PushReq) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *PushReq) GetCallback() string {
	if m != nil {
		return m.Callback
	}
	return ""
}

func (m *PushReq) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type PushResp struct {
}

func (m *PushResp) Reset()                    { *m = PushResp{} }
func (m *PushResp) String() string            { return proto1.CompactTextString(m) }
func (*PushResp) ProtoMessage()               {}
func (*PushResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type CometPingReq struct {
}

func (m *CometPingReq) Reset()                    { *m = CometPingReq{} }
func (m *CometPingReq) String() string            { return proto1.CompactTextString(m) }
func (*CometPingReq) ProtoMessage()               {}
func (*CometPingReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type CometPingResp struct {
}

func (m *CometPingResp) Reset()                    { *m = CometPingResp{} }
func (m *CometPingResp) String() string            { return proto1.CompactTextString(m) }
func (*CometPingResp) ProtoMessage()               {}
func (*CometPingResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func init() {
	proto1.RegisterType((*PushReq)(nil), "proto.PushReq")
	proto1.RegisterType((*PushResp)(nil), "proto.PushResp")
	proto1.RegisterType((*CometPingReq)(nil), "proto.CometPingReq")
	proto1.RegisterType((*CometPingResp)(nil), "proto.CometPingResp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for MsgPushService service

type MsgPushServiceClient interface {
	MsgPush(ctx context.Context, in *PushReq, opts ...grpc.CallOption) (*PushResp, error)
	WRRMsgPush(ctx context.Context, in *PushReq, opts ...grpc.CallOption) (*PushResp, error)
	Ping(ctx context.Context, in *CometPingReq, opts ...grpc.CallOption) (*CometPingResp, error)
}

type msgPushServiceClient struct {
	cc *grpc.ClientConn
}

func NewMsgPushServiceClient(cc *grpc.ClientConn) MsgPushServiceClient {
	return &msgPushServiceClient{cc}
}

func (c *msgPushServiceClient) MsgPush(ctx context.Context, in *PushReq, opts ...grpc.CallOption) (*PushResp, error) {
	out := new(PushResp)
	err := grpc.Invoke(ctx, "/proto.msgPushService/MsgPush", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgPushServiceClient) WRRMsgPush(ctx context.Context, in *PushReq, opts ...grpc.CallOption) (*PushResp, error) {
	out := new(PushResp)
	err := grpc.Invoke(ctx, "/proto.msgPushService/WRRMsgPush", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgPushServiceClient) Ping(ctx context.Context, in *CometPingReq, opts ...grpc.CallOption) (*CometPingResp, error) {
	out := new(CometPingResp)
	err := grpc.Invoke(ctx, "/proto.msgPushService/Ping", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for MsgPushService service

type MsgPushServiceServer interface {
	MsgPush(context.Context, *PushReq) (*PushResp, error)
	WRRMsgPush(context.Context, *PushReq) (*PushResp, error)
	Ping(context.Context, *CometPingReq) (*CometPingResp, error)
}

func RegisterMsgPushServiceServer(s *grpc.Server, srv MsgPushServiceServer) {
	s.RegisterService(&_MsgPushService_serviceDesc, srv)
}

func _MsgPushService_MsgPush_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgPushServiceServer).MsgPush(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.msgPushService/MsgPush",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgPushServiceServer).MsgPush(ctx, req.(*PushReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MsgPushService_WRRMsgPush_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgPushServiceServer).WRRMsgPush(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.msgPushService/WRRMsgPush",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgPushServiceServer).WRRMsgPush(ctx, req.(*PushReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MsgPushService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CometPingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgPushServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.msgPushService/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgPushServiceServer).Ping(ctx, req.(*CometPingReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _MsgPushService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.msgPushService",
	HandlerType: (*MsgPushServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MsgPush",
			Handler:    _MsgPushService_MsgPush_Handler,
		},
		{
			MethodName: "WRRMsgPush",
			Handler:    _MsgPushService_WRRMsgPush_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _MsgPushService_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "push.proto",
}

func init() { proto1.RegisterFile("push.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 295 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x90, 0xcf, 0x4e, 0xf3, 0x30,
	0x10, 0xc4, 0xbf, 0xfe, 0x4b, 0xd2, 0xfd, 0x20, 0x45, 0x4b, 0x85, 0x56, 0x39, 0xa1, 0x9c, 0x38,
	0xa0, 0x22, 0xd1, 0x47, 0xe0, 0xc4, 0x01, 0xa9, 0x0a, 0x42, 0x9c, 0x53, 0x67, 0x49, 0xa2, 0x26,
	0xb5, 0x1b, 0xbb, 0x08, 0xce, 0xbc, 0x0a, 0x0f, 0x8a, 0x6c, 0xa7, 0xa8, 0x88, 0x13, 0x27, 0xef,
	0x6f, 0x56, 0xe3, 0x19, 0x2d, 0x80, 0xda, 0xeb, 0x6a, 0xa1, 0x3a, 0x69, 0x24, 0x4e, 0xdc, 0x93,
	0x7e, 0x0c, 0x21, 0x5c, 0xed, 0x75, 0x95, 0xf1, 0x0e, 0xcf, 0x60, 0xb4, 0xe1, 0x77, 0x1a, 0x5c,
	0x0e, 0xae, 0xa6, 0x99, 0x1d, 0xf1, 0x02, 0x02, 0x7e, 0x53, 0x75, 0xc7, 0x34, 0x74, 0x62, 0x4f,
	0x48, 0x10, 0xda, 0xaf, 0x9e, 0x8c, 0xa0, 0x91, 0x5b, 0x1c, 0x10, 0x11, 0xc6, 0x82, 0x3b, 0x43,
	0x63, 0x27, 0xbb, 0x19, 0x13, 0x88, 0x54, 0x93, 0x9b, 0x17, 0xd9, 0xb5, 0x34, 0x71, 0xfa, 0x37,
	0xe3, 0x1c, 0x26, 0xaa, 0x92, 0x5b, 0xa6, 0xc0, 0x2d, 0x3c, 0xd8, 0x26, 0xad, 0x2e, 0x29, 0xf4,
	0x4d, 0x5a, 0x5d, 0xda, 0x26, 0x36, 0xe2, 0xbe, 0xa0, 0xc8, 0x37, 0xf1, 0x64, 0xfd, 0x46, 0xaa,
	0x5a, 0xd0, 0xd4, 0xfb, 0x1d, 0xd8, 0x44, 0x91, 0x37, 0xcd, 0x3a, 0x17, 0x1b, 0x02, 0x9f, 0x78,
	0x60, 0xd7, 0x50, 0x16, 0x4c, 0xff, 0xfb, 0x86, 0xb2, 0xe0, 0x14, 0x20, 0xf2, 0x47, 0xd0, 0x2a,
	0x8d, 0xe1, 0xe4, 0x4e, 0xb6, 0x6c, 0x56, 0xf5, 0xb6, 0xcc, 0x78, 0x97, 0xce, 0xe0, 0xf4, 0x88,
	0xb5, 0xba, 0xfd, 0x1c, 0x40, 0xdc, 0xea, 0xd2, 0x1a, 0x1e, 0xb9, 0x7b, 0xad, 0x05, 0xe3, 0x35,
	0x84, 0x0f, 0x5e, 0xc1, 0xd8, 0xdf, 0x77, 0xd1, 0x1f, 0x35, 0x99, 0xfd, 0x60, 0xad, 0xd2, 0x7f,
	0x78, 0x03, 0xf0, 0x9c, 0x65, 0x7f, 0x30, 0x2c, 0x61, 0x6c, 0xd3, 0xf1, 0xbc, 0x5f, 0x1d, 0xf7,
	0x4b, 0xe6, 0xbf, 0x45, 0x6b, 0x5a, 0x07, 0x4e, 0x5e, 0x7e, 0x05, 0x00, 0x00, 0xff, 0xff, 0x90,
	0xc4, 0x6b, 0xe6, 0xf5, 0x01, 0x00, 0x00,
}
